# Site settings
title: Clément Uster
description: "Hi! My name is Clément Uster, I'm a software engineer, focused on web development. I mainly use javascript, java and ruby. The purpose of this blog is to share some tests and thoughts about programming."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
